### ISSUE TITLE
[Airbrake] [Production] 765: unexpected token at 'app/node_modules/sayduck-gltf-pipeline/shared.js:95       throw new Error( util.format.apply(util.format, Array.prototype.slice.call(arguments)) )       ^  Error: (node:4261) UnhandledPromiseRejectionWa...

### ISSUE THREAD

**Issue by sayduck-daniel** [Sayduck/sayduck-gltf-pipeline#11]
**Airbrake error:** [#5139](https://herokuaccountapp97997150herokucom.airbrake.io/projects/185905/groups/2367460161454545139)
**Airbrake project:** sayduck-api

**Error type:** `JSON::ParserError`
**Error message:** `` 765: unexpected token at 'app/node_modules/sayduck-gltf-pipeline/shared.js:95       throw new Error( util.format.apply(util.format, Array.prototype.slice.call(arguments)) )       ^  Error: (node:4261) UnhandledPromiseRejectionWarning: Error: Error: { Error     at new RuntimeError (/app/node_modules/cesium/Source/Core/RuntimeError.js:42:19)     at finishLoading (/app/node_modules/obj2gltf/lib/loadObj.js:425:15)     at /app/node_modules/obj2gltf/lib/loadObj.js:401:20     at tryCatcher (/app/nod... ``
**Where:** `sidekiq#GenerateMeshAssetsWorker`
**Occurred at:** Dec 11, 2018 11:20:43 UTC
**First seen at:** Dec 11, 2018 11:20:43 UTC
**Occurrences:** 0 (0 since last deploy on Dec 11, 2018 11:10:45 UTC)
**Severity:** `error`

**URL:** `<no information>`
**File:** `/PROJECT_ROOT/vendor/ruby-2.5.1/lib/ruby/2.5.0/json/common.rb`

**Backtrace:**
```
/PROJECT_ROOT/vendor/ruby-2.5.1/lib/ruby/2.5.0/json/common.rb:156:in parse
/PROJECT_ROOT/vendor/ruby-2.5.1/lib/ruby/2.5.0/json/common.rb:156:in parse
/PROJECT_ROOT/app/services/generate_mesh_assets_service.rb:83:in exec_cmd
/PROJECT_ROOT/app/services/generate_mesh_assets_service.rb:78:in json
```

**Comment by sayduck-daniel** [comment]
I got that, no idea what product or what this is.
